### ISSUE TITLE
regarding In parameter move from last use

### ISSUE THREAD

**Issue by shaneasd** [hsutter/708#19] opened 2020-12-29 10:42 UTC
My comment pertains to #18 but I've kept it separate to dissociate the issue of the implementation not matching the spec from the question of whether the spec is a good idea. For convenience the issue is:

> The last line prints `1`, but it should print `2` because `f(param)` is the definite last use of the `param`... Godbolt repro: https://cppx.godbolt.org/z/17noYP
> 
> ```
> struct X {}; 
> void f(X const&) { cout << "1\n"; } 
> void f(X &&    ) { cout << "2\n"; } 
> 
> void test(in X param) { f(param); }
> 
> int main() { 
>     X x; 
>     test(x);       // 1 
> 
>     test(X());     // *** should be 2
> }
> ```

I find that assertion somewhat surprising. So much so that I believed it to be incorrect until I went and found the relevant section of the paper
> Note that all of the following are compatible with calling existing functions. For example, an inparameter is simply treated as a constlvalue for all purposes including for passing it onward to an existing overload set, **ex-cept that the definite last use treats it as an rvalue** (only if the actual argument is an rvalueand the use would be legal for an rvalue) which naturally selects any rvalue overloads for the function it’s being passed to

The reasons I find it surprising are:

1. It's a special case for an otherwise pretty explainable rule. I can certainly see the value in it. I think of it as akin to something like copy elision where its a special rule that breaks the usual rules to gain performance that you couldn't otherwise get conveniently. I don't know if that trade off is worthwhile here. I would definitely get tripped up by this but it's not clear whether overlooking this special rule would result in a bug (bad), a performance hit (kinda bad) or just a missed opportunity for briefer/faster code (not really a problem).

2. I think that in this code
```
void foo(X&& x) //or (X x) or (X& x)
{
   remember = &x;
   consume(std::move(x))
}
```
it's apparent that there's probably a bug but in the somewhat equivalent code
```
void foo(in X x)
{
   remember = &x;
   consume(x);
}
```
I think the bug is less obvious. I admit the example is quite contrived. I don't know how often it would come up.

3. related to 2, I can't see what the difference is between the last use of an ```in X``` and the last use of a ```X&&``` it seems to me like it's equally safe to move from. i.e. I think if you have to have a std::move here ```foo(X&& x) { consume(std::move(x)); }``` then you should have to on ```foo(in X x) { consume(std::move(x)); }```. Unfortunately this has the issue that you don't know if x is an X&& or not in the latter case and you don't want to be std::moving a const&. However I think the argument applies in reverse as well. If it's acceptable to omit the std::move in the ```in``` example then why isn't it in the ```X&&``` example? Is it somehow safer? Perhaps std::move should be implicit in the X&& case as well. I don't know but I wonder if it's to mitigate against bugs like in 2.

I'm not totally confident in any of the points above so hopefully there's merit to at least one of them and it's not just my understanding that's the problem.

**Comment by hsutter** [comment] 2021-01-05 00:20
Thanks! I think this is covered in the paper, so I'll close this as "by design," but here's a quick answer...

1) Yes, the design is to follow and automate today's guidance for non-cheaply-copyable in parameters, which is "pass by `const&`, and if you want to optimize for rvalues overload on `&&` and move from the last use." That's what we already teach as a best practice today, but it's manual and often tedious to write. This automates it, including the optimization.

If we find it's surprising we can revisit this, mostly that if need a mode that doesn't do this and always copies then we'd likely consider an additional "always copy" mode.

2&3) In this proposal, the equivalent for `foo(X&&)` would be `foo(move X)`, not an `in` parameter.

Thanks again.

**Closed by hsutter** 2021-01-05 00:20 UTC
Labels: by design
